# Generated by Django 4.2.6 on 2024-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=90)),
                ('area', models.CharField(choices=[('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Environment', 'Environment'), ('Human Right', 'Human Right')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ngo_info',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
