# Generated by Django 4.2.6 on 2024-05-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userinfo_alter_ngo_info_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='fname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='lname',
        ),
    ]
