# Generated by Django 4.2.6 on 2024-05-26 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_fname_userinfo_username_remove_userinfo_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
