# Generated by Django 4.2.6 on 2024-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='created_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cemail',
            field=models.EmailField(max_length=254, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cname',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cphone',
            field=models.CharField(max_length=10, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='campaign',
            name='edate',
            field=models.DateField(null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='campaign',
            name='goalamount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='campaign',
            name='sdate',
            field=models.DateField(auto_now_add=True, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(max_length=100, null='False'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=100, null='False'),
        ),
    ]
