# Generated by Django 4.2.6 on 2024-06-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_campaign_ngoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_id',
            field=models.TextField(max_length=10, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='ngo_info',
            name='ngoid',
            field=models.CharField(max_length=3, null='False'),
            preserve_default='False',
        ),
    ]
