# Generated by Django 4.2.6 on 2024-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_campaign_campaign_id_ngo_info_ngoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ngoid',
            field=models.TextField(max_length=10, null='False'),
        ),
    ]
