# Generated by Django 4.2.6 on 2024-06-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_campaign_ngoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='ngoid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.ngo_info'),
        ),
        migrations.AlterField(
            model_name='ngo_info',
            name='ngoid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
